FOLDER_TEMPLATES = {
    "STANDARD": [
           # HÀNH CHÍNH
    "HANH-CHINH_{TENVT}",

    # TAI-LIEU-CÔNG TY — NĂM
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/1-HOA-DON-MUA/QUÝ 1",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/1-HOA-DON-MUA/QUÝ 2",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/1-HOA-DON-MUA/QUÝ 3",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/1-HOA-DON-MUA/QUÝ 4",

    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/2-HOA-DON-BAN/QUÝ 1",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/2-HOA-DON-BAN/QUÝ 2",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/2-HOA-DON-BAN/QUÝ 3",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/2-HOA-DON-BAN/QUÝ 4",

    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/3-HOP-DONG-KINH-TE/HOP-DONG-BAN",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/3-HOP-DONG-KINH-TE/HOP-DONG-KHAC",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/3-HOP-DONG-KINH-TE/HOP-DONG-MUA",

    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/4-SAO-KE-NGAN-HANG",

    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/5-LUONG/BANG-CHAM-CONG",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/5-LUONG/BAO-HIEM-XA-HOI",

    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/6-HANG-TON-KHO-VA-GIA-THANH",
    "TAI-LIEU-CONG-TY_{TENVT}/{Y}/7-KHAC",

    # 🟩 TAI-LIEU-CỐ ĐỊNH — CHUYỂN VÀO TRONG TAI-LIEU-CÔNG TY
    "TAI-LIEU-CONG-TY_{TENVT}/TAI-LIEU-CO-DINH/KHAC",
    "TAI-LIEU-CONG-TY_{TENVT}/TAI-LIEU-CO-DINH/LAO-DONG",
    "TAI-LIEU-CONG-TY_{TENVT}/TAI-LIEU-CO-DINH/PHAP-LY",
    "TAI-LIEU-CONG-TY_{TENVT}/TAI-LIEU-CO-DINH/QUY-TRINH",

    # TAI-LIEU-THUẾ
    "TAI-LIEU-THUE_{TENVT}/{Y}/GIA-TRI-GIA-TANG",

    "TAI-LIEU-THUE_{TENVT}/{Y}/KE-TOAN/QUY-1",
    "TAI-LIEU-THUE_{TENVT}/{Y}/KE-TOAN/QUY-2",
    "TAI-LIEU-THUE_{TENVT}/{Y}/KE-TOAN/QUY-3",
    "TAI-LIEU-THUE_{TENVT}/{Y}/KE-TOAN/QUY-4-VA-CA-NAM",

    "TAI-LIEU-THUE_{TENVT}/{Y}/THU-NHAP-CA-NHAN",
    "TAI-LIEU-THUE_{TENVT}/{Y}/THU-NHAP-DOANH-NGHIEP",
    ]
}
